name: Deploy

on: [push]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Install dotnet
      - name: Installing dotnet
        if: always()
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.202'

      # Do the report magic
      - name: Generate .html report
        run: sudo dotnet ./ExtentReports/ExtentReportsDotNetCLI.dll -i=artifacts/editmode-results.xml -o artifacts/editmode/report
        if: always()          

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: artifacts

          
  build:
    name: Build
    needs: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        id: build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows
          allowDirtyBuild: true
          versioning: Semantic 
          buildName: GAMEJAM 20201
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.build.outputs.buildVersion }}
          release_name: Release ${{ steps.build.outputs.buildVersion }}

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
